In [4]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
import numpy as np
import os

In [2]:
## Exportaciones 
Exp_ene = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_enero.xlsx')
Exp_feb = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_febrero.xlsx')
Exp_mar = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_marzo.xlsx')
Exp_abr = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_abril.xlsx')
Exp_may = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_mayo.xlsx')
Exp_jun = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_junio.xlsx')
Exp_jul = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_julio.xlsx')
Exp_ago = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_agosto.xlsx')
Exp_sep = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_septiembre.xlsx')
Exp_oct = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025\\Exp_octubre.xlsx')

In [3]:
Exp_ene['Mes'] = 'Enero'
Exp_feb['Mes'] = 'Febrero'
Exp_mar['Mes'] = 'Marzo'
Exp_abr['Mes'] = 'Abril'
Exp_may['Mes'] = 'Mayo'
Exp_jun['Mes'] = 'Junio'
Exp_jul['Mes'] = 'Julio'
Exp_ago['Mes'] = 'Agosto'
Exp_sep['Mes'] = 'Septiembre'
Exp_oct['Mes'] = 'Octubre'

In [4]:
Exportaciones = pd.concat([
    Exp_ene, Exp_feb, Exp_mar, Exp_abr, 
    Exp_may, Exp_jun, Exp_jul, Exp_ago, 
    Exp_sep, Exp_oct
], ignore_index=True)

In [5]:
## Importaciones
Imp_ene = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_enero.xlsx')
Imp_feb = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_febrero.xlsx')
Imp_mar = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_marzo.xlsx')
Imp_abr = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_abril.xlsx')
Imp_may = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_mayo.xlsx')
Imp_jun = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_junio.xlsx')
Imp_jul = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_julio.xlsx')
Imp_ago = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_agosto.xlsx')
Imp_sep = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_septiembre.xlsx')
Imp_oct = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones 2025\\Imp_octubre.xlsx')

In [6]:
Imp_ene['Mes'] = 'Enero'
Imp_feb['Mes'] = 'Febrero'
Imp_mar['Mes'] = 'Marzo'
Imp_abr['Mes'] = 'Abril'
Imp_may['Mes'] = 'Mayo'
Imp_jun['Mes'] = 'Junio'
Imp_jul['Mes'] = 'Julio'
Imp_ago['Mes'] = 'Agosto'
Imp_sep['Mes'] = 'Septiembre'
Imp_oct['Mes'] = 'Octubre'

In [7]:
Importaciones = pd.concat([
    Imp_ene, Imp_feb, Imp_mar, Imp_abr, 
    Imp_may, Imp_jun, Imp_jul, Imp_ago, 
    Imp_sep, Imp_oct
], ignore_index=True)

In [8]:
def clasificacion_empresa(x):
    if x > 100000000:
        return 'Operación > 100 mm'
    elif x > 50000000:
        return 'Operación > 50 mm'
    elif x > 30000000:
        return 'Operación > 30 mm'
    elif x > 20000000:
        return 'Operación > 20 mm'
    elif x > 10000000:
        return 'Operación > 10 mm'
    elif x > 5000000:
        return 'Operación > 5 mm'
    elif x > 2000000:
        return 'Operación > 2 mm'
    elif x > 1000000:
        return 'Operación > 1 mm'
    else:
        return 'Montos menores'

In [9]:
Exportaciones['Calificacion tamaño (Exportacion)'] =  Exportaciones['Total FOB'].apply(clasificacion_empresa)
Importaciones['Calificacion tamaño (Importacion)'] = Importaciones['Monto (USD)'].apply(clasificacion_empresa)

In [10]:
Exportaciones['Tipo de operación'] = 'Exportación'
Importaciones['Tipo de operación'] = 'Importación'

In [11]:
Exportaciones.head()

,Empresa,Total FOB,Peso Neto,Peso Bruto,% FOB,Mes,Calificacion tamaño (Exportacion),Tipo de operación
0,MINERA SAN CRISTOBAL SA,62095476.0,2.233154e+07,45713676.0,0.150,Enero,Operación > 50 mm,Exportación
1,CORPORACION MINERA DE BOLIVIA,27743456.0,1.692868e+06,3170971.0,0.067,Enero,Operación > 20 mm,Exportación
2,Y P F B,15206154.0,5.570198e+07,55833184.0,0.037,Enero,Operación > 10 mm,Exportación
3,INDUSTRIAS DE ACEITE SA,15050449.0,3.163646e+07,31637068.0,0.036,Enero,Operación > 10 mm,Exportación
4,ORBOL SA,14636607.0,1.961600e+02,235.0,0.035,Enero,Operación > 10 mm,Exportación

In [12]:
Exportaciones.shape

(6765, 8)

In [13]:
Exportaciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6765 entries, 0 to 6764
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Empresa                            6765 non-null   object
 1   Total FOB                          6765 non-null   float64
 2   Peso Neto                          6765 non-null   float64
 3   Peso Bruto                         6765 non-null   float64
 4   % FOB                              6765 non-null   float64
 5   Mes                                6765 non-null   object
 6   Calificacion tamaño (Exportacion)  6765 non-null   object
 7   Tipo de operación                  6765 non-null   object
dtypes: float64(4), object(4)
memory usage: 422.9+ KB

In [14]:
Importaciones.head()

,Empresa,Monto (USD),Peso Neto,Peso Bruto,% Monto,Mes,Calificacion tamaño (Exportacion),Tipo de operación
0,Y P F B,147165856.0,1.584447e+08,1.584447e+08,0.215,Enero,Operación > 100 mm,Importación
1,EMBOTELLADORAS BOLIVIANAS UNIDAS SA,11557368.0,2.591950e+06,2.702971e+06,0.017,Enero,Operación > 10 mm,Importación
2,CERVECERIA BOLIVIANA NACIONAL SA,9175344.0,5.777904e+06,6.570176e+06,0.013,Enero,Operación > 5 mm,Importación
3,FINNING BOLIVIA SA (FINNING),7756600.0,4.008807e+05,4.105841e+05,0.011,Enero,Operación > 5 mm,Importación
4,TOYOSA SA,7528899.0,5.507489e+05,5.542109e+05,0.011,Enero,Operación > 5 mm,Importación

In [15]:
Importaciones.shape

(10000, 8)

In [16]:
Importaciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Empresa                            10000 non-null  object
 1   Monto (USD)                        10000 non-null  float64
 2   Peso Neto                          10000 non-null  float64
 3   Peso Bruto                         10000 non-null  float64
 4   % Monto                            10000 non-null  float64
 5   Mes                                10000 non-null  object
 6   Calificacion tamaño (Exportacion)  10000 non-null  object
 7   Tipo de operación                  10000 non-null  object
dtypes: float64(4), object(4)
memory usage: 625.1+ KB

In [17]:
df_final = pd.concat([Exportaciones, Importaciones], ignore_index=True)

In [18]:
df_final.head()

,Empresa,Total FOB,Peso Neto,Peso Bruto,% FOB,Mes,Calificacion tamaño (Exportacion),Tipo de operación,Monto (USD),% Monto
0,MINERA SAN CRISTOBAL SA,62095476.0,2.233154e+07,45713676.0,0.150,Enero,Operación > 50 mm,Exportación,NaN,NaN
1,CORPORACION MINERA DE BOLIVIA,27743456.0,1.692868e+06,3170971.0,0.067,Enero,Operación > 20 mm,Exportación,NaN,NaN
2,Y P F B,15206154.0,5.570198e+07,55833184.0,0.037,Enero,Operación > 10 mm,Exportación,NaN,NaN
3,INDUSTRIAS DE ACEITE SA,15050449.0,3.163646e+07,31637068.0,0.036,Enero,Operación > 10 mm,Exportación,NaN,NaN
4,ORBOL SA,14636607.0,1.961600e+02,235.0,0.035,Enero,Operación > 10 mm,Exportación,NaN,NaN

## Generacion de tabla categorica general

In [19]:
Exportaciones_int = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Exportaciones 2025.xlsx')
Importaciones_int = pd.read_excel('D:\\Usuarios\\RSanabria\\OneDrive - HANSA\\Escritorio\\Exportaciones importaciones\\Importaciones.xlsx')

In [20]:
Exportaciones_int.head()

,Empresa,Total FOB,Peso Neto,Peso Bruto,% FOB,Rubro,Sub Rubro (Exportacion),Calificacion tamaño (Exportacion),Sede de Operaciones
0,MINERA SAN CRISTOBAL SA,644957568.0,2.435243e+08,4.992411e+08,0.106,Mineria,"zinc, plata, plomo",Exportación FOB > 100 mm,Potosi
1,CORPORACION MINERA DE BOLIVIA,478221184.0,2.499584e+07,4.381348e+07,0.079,Mineria,Estaño,Exportación FOB > 100 mm,La Paz
2,DORIMET SRL,349743680.0,3.596840e+03,4.193160e+03,0.058,Mineria,Oro,Exportación FOB > 100 mm,Santa Cruz De La Sierra
3,INDUSTRIAS DE ACEITE SA,252778336.0,5.315083e+08,5.318765e+08,0.042,Agroalimenticia,Soya,Exportación FOB > 100 mm,Santa Cruz De La Sierra
4,ORBOL SA,201042080.0,2.500770e+03,2.948280e+03,0.033,Mineria,Oro,Exportación FOB > 100 mm,La Paz

In [21]:
Exportaciones_int.groupby(['Sede de Operaciones','Rubro', 'Empresa']).Rubro.count()

Sede de Operaciones  Rubro            Empresa
Beni                 Agroindustria    BENEF DE ALMENDRAS R BOWLES RIVERO         1
                                      BENEF DE NUECES BOLIVIANAS SRL             1
                                      BENEFICIADORA DE ALMENDRAS MAILY SRL       1
                                      BENEFICIADORA DE ALMENDRAS URKUPIÑA SRL    1
                                      BENEFICIADORA SAN AGUSTIN SRL              1
                                                                                ..
Sucre                Agroalimenticia  RONALD ROGER REYNALES VILLALBA             1
                     Agroindustria    UNEC SA UNIDAD DE NEGOCIOS DE ES           1
                     Textil           FCA DE SOMBREROS CHUQUISACA SRL            1
                                      TEXTILES BURCAL SRL                        1
Tarija               Otros            INDUSTRIAS AGRICOLAS DE BERMEJO SA         1
Name: Rubro, Length: 1000, dtype: int64

In [22]:
Importaciones_int.head()

,Empresa,Monto (USD),Peso Neto,Peso Bruto,% Monto,Rubro,Sub Rubro (Importacion),Calificacion tamaño (Exportacion),Operaciones
0,CERVECERIA BOLIVIANA NACIONAL SA,103767928.0,68999920.0,74900008.0,0.012,Bebidas,NaN,Importación FOB > 100 mm,La Paz
1,MINERA SAN CRISTOBAL SA,95449288.0,59291520.0,59572808.0,0.011,Mineria,NaN,Importación FOB > 50 mm,La Paz
2,EMBOTELLADORAS BOLIVIANAS UNIDAS SA,87419320.0,17746814.0,18658812.0,0.010,Bebidas,NaN,Importación FOB > 50 mm,La Paz
3,IMCRUZ COMERCIAL SA,72485984.0,9248889.0,9557214.0,0.009,Automotriz,NaN,Importación FOB > 50 mm,Santa Cruz De La Sierra
4,TOYOSA SA,63475032.0,4556943.0,4603013.5,0.008,Automotriz,NaN,Importación FOB > 50 mm,La Paz

In [23]:
Exportaciones_int.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Empresa                            1000 non-null   object
 1   Total FOB                          1000 non-null   float64
 2   Peso Neto                          997 non-null    float64
 3   Peso Bruto                         997 non-null    float64
 4   % FOB                              997 non-null    float64
 5   Rubro                              1000 non-null   object
 6   Sub Rubro (Exportacion)            1000 non-null   object
 7   Calificacion tamaño (Exportacion)  1000 non-null   object
 8   Sede de Operaciones                1000 non-null   object
dtypes: float64(4), object(5)
memory usage: 70.4+ KB

In [24]:
Exp1 = Exportaciones_int[['Empresa','Rubro','Sede de Operaciones', 'Sub Rubro (Exportacion)']]
Imp1 = Importaciones_int[['Empresa','Rubro','Operaciones', 'Sub Rubro (Importacion)']]

In [25]:
Empresa = Exp1.merge(Imp1, on='Empresa', how = 'outer')

In [26]:
Empresa.groupby(['Sede de Operaciones','Rubro_x', 'Empresa']).Rubro_x.count()

Sede de Operaciones  Rubro_x          Empresa
Beni                 Agroindustria    BENEF DE ALMENDRAS R BOWLES RIVERO         1
                                      BENEF DE NUECES BOLIVIANAS SRL             1
                                      BENEFICIADORA DE ALMENDRAS MAILY SRL       1
                                      BENEFICIADORA DE ALMENDRAS URKUPIÑA SRL    1
                                      BENEFICIADORA SAN AGUSTIN SRL              1
                                                                                ..
Sucre                Agroalimenticia  RONALD ROGER REYNALES VILLALBA             1
                     Agroindustria    UNEC SA UNIDAD DE NEGOCIOS DE ES           1
                     Textil           FCA DE SOMBREROS CHUQUISACA SRL            1
                                      TEXTILES BURCAL SRL                        1
Tarija               Otros            INDUSTRIAS AGRICOLAS DE BERMEJO SA         1
Name: Rubro_x, Length: 1000, dtype: int64

In [27]:
Empresa.groupby(['Operaciones','Rubro_y', 'Empresa']).Rubro_y.count()

Operaciones              Rubro_y               Empresa
Beni                     Bebidas               NUDELPA LTDA                          1
Cochabamba               Acero - Construccion  IMPORTADORA CAMPERO SRL               1
                         Agroindustria         CAMPOSOL SRL                          1
                         Alimentos             ARANIBAR CHINCHILLA JUAN CARLOS       1
                                               PIL ANDINA SA                         1
                                                                                    ..
Santa Cruz De La Sierra  Tecnologia            DISTRIBUIDOR MAYORISTA DE COMPUTAD    1
                                               TELEFONICA CELULAR DE BOLIVIA SA      1
                         Vidrio                INDUVIS SRL                           1
Sucre                    Textil                FCA DE SOMBREROS CHUQUISACA SRL       1
Tarija                   Consumo Masivo        FAIR PLAY SRL                         1
Name: Rubro_y, Length: 303, dtype: int64

In [28]:
Empresa = Empresa.fillna('S/C')

In [29]:
Empresa.head(25)

,Empresa,Rubro_x,Sede de Operaciones,Sub Rubro (Exportacion),Rubro_y,Operaciones,Sub Rubro (Importacion)
0,4LLAMAS SRL,S/C,Otros,S/C,S/C,S/C,S/C
1,A & Z CUEROS SRL,Textil,Santa Cruz De La Sierra,Cuero,S/C,S/C,S/C
2,A J VIERCI SRL,S/C,Otros,S/C,S/C,Otros,S/C
3,ABASTOHOGAR SRL,S/C,S/C,S/C,S/C,Otros,S/C
4,ABIGAIL SOSA RAPU,S/C,S/C,S/C,Otros,Otros,S/C
5,ACEROS GALVANIZADOS SRL ACERGAL,S/C,S/C,S/C,Acero - Construccion,La Paz,S/C
6,ACEROS IND FERRUFINO & GARDILCIC SRL,S/C,S/C,S/C,S/C,Otros,S/C
7,ACEROSPAURITO SRL,S/C,S/C,S/C,S/C,Otros,S/C
8,ACRICOLOR ARTE SRL,S/C,Otros,S/C,S/C,Otros,S/C
9,ACRICOLOR GRAFICA SRL,S/C,S/C,S/C,S/C,Otros,S/C
10,ADALID OMONTE GALINDO,S/C,S/C,S/C,S/C,Otros,S/C
11,ADEPAO METAL VIRGEN DE COPACABANA,S/C,Otros,S/C,S/C,S/C,S/C
12,ADIPHARM SRL,S/C,S/C,S/C,S/C,Otros,S/C
13,ADM DE TARJETAS DE CREDITO,S/C,S/C,S/C,S/C,Otros,S/C
14,ADMINISTRADORA DE ALIMENTOS NORTE QUIJARRO SRL,S/C,Otros,S/C,S/C,S/C,S/C
15,ADOLFO DONALD MEALLA,S/C,S/C,S/C,S/C,Otros,S/C
16,ADUBOS SRL,S/C,S/C,S/C,S/C,Otros,S/C
17,AEROPIX SRL,S/C,S/C,S/C,S/C,Otros,S/C
18,AG BOLIVIANA DE ENERGIA NUCLEAR,S/C,S/C,S/C,Energia,La Paz,S/C
19,AGAPO DURAN SOLIS,S/C,S/C,S/C,S/C,Otros,S/C
20,AGENCIAS GENERALES SA,S/C,S/C,S/C,Mayorista - Construccion,Santa Cruz De La Sierra,S/C
21,AGIMEX SRL,S/C,S/C,S/C,S/C,Otros,S/C
22,AGRIMASTER SRL,S/C,S/C,S/C,S/C,Otros,S/C
23,AGRIPAC BOLIVIANA CIA LTDA,Agroindustria,Santa Cruz De La Sierra,Maiz para siembra,Agroindustria,Santa Cruz De La Sierra,S/C
24,AGRISAM SRL,S/C,Otros,S/C,S/C,S/C,S/C

In [30]:
Empresa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1822 entries, 0 to 1821
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Empresa                  1822 non-null   object
 1   Rubro_x                  1822 non-null   object
 2   Sede de Operaciones      1822 non-null   object
 3   Sub Rubro (Exportacion)  1822 non-null   object
 4   Rubro_y                  1822 non-null   object
 5   Operaciones              1822 non-null   object
 6   Sub Rubro (Importacion)  1822 non-null   object
dtypes: object(7)
memory usage: 99.8+ KB

In [31]:
def operaciones_unidos (x):
    if x['Sede de Operaciones'] != 'S/C':
        return x['Sede de Operaciones']
    else:
        return x['Operaciones']

In [32]:
def rubros_unidos (x):
    if x['Rubro_x'] != 'S/C':
        return x['Rubro_x']
    else:
        return x['Rubro_y']

In [33]:
Empresa['Rubro'] = Empresa.apply(rubros_unidos,  axis = 1)
Empresa['Operaciones Nacionales'] = Empresa.apply(operaciones_unidos,  axis = 1)

In [34]:
Empresa.drop(columns = ['Rubro_x', 'Sede de Operaciones', 'Rubro_y', 'Operaciones'], inplace = True)
Empresa

,Empresa,Sub Rubro (Exportacion),Sub Rubro (Importacion),Rubro,Operaciones Nacionales
0,4LLAMAS SRL,S/C,S/C,S/C,Otros
1,A & Z CUEROS SRL,Cuero,S/C,Textil,Santa Cruz De La Sierra
2,A J VIERCI SRL,S/C,S/C,S/C,Otros
3,ABASTOHOGAR SRL,S/C,S/C,S/C,Otros
4,ABIGAIL SOSA RAPU,S/C,S/C,Otros,Otros
...,...,...,...,...,...
1817,ZEGARRA CABRERA MARIA SUSANA,S/C,S/C,S/C,Otros
1818,ZELANDEZ SERVICES SRL,S/C,S/C,S/C,Otros
1819,ZEPOL LTDA,S/C,S/C,S/C,Otros
1820,ZHANGYI - EXPOMADERA,S/C,S/C,S/C,Otros
1821,ZTE BOLIVIA SRL,S/C,S/C,Tecnologia,Otros

In [35]:
Empresa.groupby(['Operaciones Nacionales','Rubro', 'Empresa']).Rubro.count()

Operaciones Nacionales  Rubro           Empresa
Beni                    Agroindustria   BENEF DE ALMENDRAS R BOWLES RIVERO         1
                                        BENEF DE NUECES BOLIVIANAS SRL             1
                                        BENEFICIADORA DE ALMENDRAS MAILY SRL       1
                                        BENEFICIADORA DE ALMENDRAS URKUPIÑA SRL    1
                                        BENEFICIADORA SAN AGUSTIN SRL              1
                                                                                  ..
Sucre                   Agroindustria   UNEC SA UNIDAD DE NEGOCIOS DE ES           1
                        Textil          FCA DE SOMBREROS CHUQUISACA SRL            1
                                        TEXTILES BURCAL SRL                        1
Tarija                  Consumo Masivo  FAIR PLAY SRL                              1
                        Otros           INDUSTRIAS AGRICOLAS DE BERMEJO SA         1
Name: Rubro, Length: 1822, dtype: int64

# Tabla Final

In [36]:
df_final = df_final.merge(Empresa, on = 'Empresa', how = 'outer')

In [37]:
df_final.head()

,Empresa,Total FOB,Peso Neto,Peso Bruto,% FOB,Mes,Calificacion tamaño (Exportacion),Tipo de operación,Monto (USD),% Monto,Sub Rubro (Exportacion),Sub Rubro (Importacion),Rubro,Operaciones Nacionales
0,2M MENMARQ SRL,NaN,64932.0,65212.000000,NaN,Abril,Montos menores,Importación,165351.4375,0.0,NaN,NaN,NaN,NaN
1,4LLAMAS SRL,94100.796875,7410.0,7506.000000,0.0,Enero,Montos menores,Exportación,NaN,NaN,S/C,S/C,S/C,Otros
2,4LLAMAS SRL,27066.000000,2100.0,2127.000000,0.0,Marzo,Montos menores,Exportación,NaN,NaN,S/C,S/C,S/C,Otros
3,4LLAMAS SRL,1512.400024,40.0,41.200001,0.0,Mayo,Montos menores,Exportación,NaN,NaN,S/C,S/C,S/C,Otros
4,A & Z CUEROS SRL,66770.546875,157179.0,159209.000000,0.0,Enero,Montos menores,Exportación,NaN,NaN,Cuero,S/C,Textil,Santa Cruz De La Sierra

In [38]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16853 entries, 0 to 16852
Data columns (total 14 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Empresa                            16853 non-null  object
 1   Total FOB                          6765 non-null   float64
 2   Peso Neto                          16765 non-null  float64
 3   Peso Bruto                         16765 non-null  float64
 4   % FOB                              6765 non-null   float64
 5   Mes                                16765 non-null  object
 6   Calificacion tamaño (Exportacion)  16765 non-null  object
 7   Tipo de operación                  16765 non-null  object
 8   Monto (USD)                        10000 non-null  float64
 9   % Monto                            10000 non-null  float64
 10  Sub Rubro (Exportacion)            12878 non-null  object
 11  Sub Rubro (Importacion)            12878 non-null  object
 12  Rubro                              12878 non-null  object
 13  Operaciones Nacionales             12878 non-null  object
dtypes: float64(6), object(8)
memory usage: 1.8+ MB

In [39]:
df_final.isna().sum()

Empresa                                  0
Total FOB                            10088
Peso Neto                               88
Peso Bruto                              88
% FOB                                10088
Mes                                     88
Calificacion tamaño (Exportacion)       88
Tipo de operación                       88
Monto (USD)                           6853
% Monto                               6853
Sub Rubro (Exportacion)               3975
Sub Rubro (Importacion)               3975
Rubro                                 3975
Operaciones Nacionales                3975
dtype: int64

columnas_numericas = [
    'Total FOB', 'Peso Neto', 'Peso Bruto', '% FOB', 
    'Monto (USD)', '% Monto']

df_final.loc[:, columnas_numericas] = df_final[columnas_numericas].fillna(0)

In [40]:
columnas_textuales = [
    'Mes',
    'Calificacion tamaño (Exportacion)',
    'Tipo de operación',
    'Sub Rubro (Exportacion)', 
    'Sub Rubro (Importacion)', 
    'Rubro', 
    'Operaciones Nacionales']

# Rellena solo las columnas textuales, manteniendo todas las demás columnas del DataFrame
df_final.loc[:, columnas_textuales] = df_final[columnas_textuales].fillna('S/C')

In [41]:
df_final.to_excel('Exp e Importaciones.xlsx', index=False)

## Tabla final V2

In [70]:
df_final = Exportaciones.merge(Importaciones, on = 'Empresa', how = 'outer')
df_final.head()

,Empresa,Total FOB,Peso Neto_x,Peso Bruto_x,% FOB,Rubro_x,Sub Rubro (Exportacion),Calificacion tamaño (Exportacion)_x,Sede de Operaciones,Monto (USD),Peso Neto_y,Peso Bruto_y,% Monto,Rubro_y,Sub Rubro (Importacion),Calificacion tamaño (Exportacion)_y,Operaciones
0,4LLAMAS SRL,1.226792e+05,9550.0,9.674200e+03,0.0,S/C,S/C,Los demás,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A & Z CUEROS SRL,1.689045e+06,3868296.5,3.917194e+06,0.0,Textil,Cuero,Exportación FOB > 1 mm,Santa Cruz De La Sierra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A J VIERCI SRL,7.536000e+04,20160.0,2.520000e+04,0.0,S/C,S/C,Los demás,Otros,4991380.5,2117113.0,2830389.750,0.001,S/C,NaN,Importación FOB > 2 mm,Otros
3,ABASTOHOGAR SRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4757400.0,676320.0,772619.125,0.001,S/C,NaN,Importación FOB > 2 mm,Otros
4,ABIGAIL SOSA RAPU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3451352.5,4878375.0,4894350.000,0.000,Otros,NaN,Importación FOB > 2 mm,Otros

In [71]:
df_final = df_final.merge(Empresa, on = 'Empresa', how = 'outer')

In [72]:
df_final.drop(columns = ['Rubro_x', 'Sede de Operaciones', 'Rubro_y', 'Operaciones'], inplace = True)
df_final.rename(columns = {'Peso Neto_x':'Peso Neto Exp.',
                          'Peso Bruto_x': 'Peso Bruto Exp.',
                          'Calificacion tamaño (Exportacion)_x': 'Calificacion tamaño (Exportacion)',
                          'Monto (USD)': 'Monto Importaciones (USD)',
                          'Peso Neto_y':'Peso Neto Imp.',
                          'Peso Bruto_y': 'Peso Bruto Imp.',
                          'Calificacion tamaño (Exportacion)_y': 'Calificacion tamaño (Importacion)'}, inplace = True)

In [73]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1820 entries, 0 to 1819
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Empresa                            1820 non-null   object
 1   Total FOB                          997 non-null    float64
 2   Peso Neto Exp.                     997 non-null    float64
 3   Peso Bruto Exp.                    997 non-null    float64
 4   % FOB                              997 non-null    float64
 5   Sub Rubro (Exportacion)            997 non-null    object
 6   Calificacion tamaño (Exportacion)  997 non-null    object
 7   Monto Importaciones (USD)          999 non-null    float64
 8   Peso Neto Imp.                     999 non-null    float64
 9   Peso Bruto Imp.                    999 non-null    float64
 10  % Monto                            999 non-null    float64
 11  Sub Rubro (Importacion)            0 non-null      float64
 12  Calificacion tamaño (Importacion)  999 non-null    object
 13  Rubro                              1820 non-null   object
 14  Operaciones Nacionales             1820 non-null   object
dtypes: float64(9), object(6)
memory usage: 213.4+ KB

In [207]:
columnas_numericas = [
    'Total FOB', 'Peso Neto Exp.', 'Peso Bruto Exp.', '% FOB', 
    'Monto Importaciones (USD)', 'Peso Neto Imp.', 'Peso Bruto Imp.','% Monto'
]
df_final.loc[:, columnas_numericas] = df_final[columnas_numericas].fillna(0)

In [208]:
columnas_textuales = [
    'Sub Rubro (Exportacion)', 
    'Calificacion tamaño (Exportacion)', 
    'Sub Rubro (Importacion)', 
    'Calificacion tamaño (Importacion)', 
    'Rubro', 
    'Operaciones Nacionales']

# Rellena solo las columnas textuales, manteniendo todas las demás columnas del DataFrame
df_final.loc[:, columnas_textuales] = df_final[columnas_textuales].fillna('S/C')

D:\Usuarios\RSanabria\AppData\Local\Temp\ipykernel_18652\3824927282.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['S/C' 'S/C' 'S/C' ... 'S/C' 'S/C' 'S/C']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_final.loc[:, columnas_textuales] = df_final[columnas_textuales].fillna('S/C')

,Empresa,Total FOB,Peso Neto Exp.,Peso Bruto Exp.,% FOB,Sub Rubro (Exportacion),Calificacion tamaño (Exportacion),Monto Importaciones (USD),Peso Neto Imp.,Peso Bruto Imp.,% Monto,Sub Rubro (Importacion),Calificacion tamaño (Importacion),Rubro,Operaciones Nacionales
0,4LLAMAS SRL,1.226792e+05,9.550000e+03,9.674200e+03,0.0,S/C,Los demás,0.000000e+00,0.000,0.000000e+00,0.000,S/C,S/C,S/C,Otros
1,A & Z CUEROS SRL,1.689045e+06,3.868296e+06,3.917194e+06,0.0,Cuero,Exportación FOB > 1 mm,0.000000e+00,0.000,0.000000e+00,0.000,S/C,S/C,Textil,Santa Cruz De La Sierra
2,A J VIERCI SRL,7.536000e+04,2.016000e+04,2.520000e+04,0.0,S/C,Los demás,4.991380e+06,2117113.000,2.830390e+06,0.001,S/C,Importación FOB > 2 mm,S/C,Otros
3,ABASTOHOGAR SRL,0.000000e+00,0.000000e+00,0.000000e+00,0.0,S/C,S/C,4.757400e+06,676320.000,7.726191e+05,0.001,S/C,Importación FOB > 2 mm,S/C,Otros
4,ABIGAIL SOSA RAPU,0.000000e+00,0.000000e+00,0.000000e+00,0.0,S/C,S/C,3.451352e+06,4878375.000,4.894350e+06,0.000,S/C,Importación FOB > 2 mm,Otros,Otros
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ZEGARRA CABRERA MARIA SUSANA,0.000000e+00,0.000000e+00,0.000000e+00,0.0,S/C,S/C,8.347769e+05,5145.000,6.371030e+03,0.000,S/C,Los demás,S/C,Otros
1816,ZELANDEZ SERVICES SRL,5.656400e+04,3.800000e+01,3.800000e+01,0.0,S/C,Los demás,0.000000e+00,0.000,0.000000e+00,0.000,S/C,S/C,S/C,Otros
1817,ZEPOL LTDA,0.000000e+00,0.000000e+00,0.000000e+00,0.0,S/C,S/C,3.286218e+06,1268674.125,1.374097e+06,0.000,S/C,Importación FOB > 2 mm,S/C,Otros
1818,ZHANGYI - EXPOMADERA,3.789016e+05,3.473000e+06,3.473000e+06,0.0,S/C,Los demás,0.000000e+00,0.000,0.000000e+00,0.000,S/C,S/C,S/C,Otros
1819,ZTE BOLIVIA SRL,3.915281e+05,2.741100e+03,3.345100e+03,0.0,S/C,Los demás,1.555737e+07,1709608.000,1.785401e+06,0.002,S/C,Importación FOB > 10 mm,Tecnologia,Otros

In [213]:
df_final.to_excel('Exp e Importaciones.xlsx', index=False)

# Importaciones por potencial cliente

## San Cristobal

In [10]:
# Lista de partidas (meses)
meses = [
    'en-feb', 'jul-sept', 'mar-jul', 'oct - en26'
]

# Ruta base
base_path = r'D:\Usuarios\RSanabria\OneDrive - HANSA\Escritorio\Business Analytics\Exportaciones importaciones\San Cristobal'

# Lista para almacenar dataframes
dfs = []

for mes in meses:
    file_path = os.path.join(base_path, f"{mes}.xlsx")  # agregar extensión
    
    if os.path.exists(file_path):
        df_temp = pd.read_excel(file_path)
        df_temp["partida"] = mes  # columna identificadora
        dfs.append(df_temp)
        print(f"Archivo cargado: {mes} ✅")
    else:
        print(f"No se encontró el archivo: {mes}")

# Unir todo
if dfs:
    df_sc = pd.concat(dfs, ignore_index=True)
    print("Carga completa ✅")
else:
    print("No se cargó ningún archivo ❌")

Archivo cargado: en-feb ✅
Archivo cargado: jul-sept ✅
Archivo cargado: mar-jul ✅
Archivo cargado: oct - en26 ✅
Carga completa ✅

In [17]:
df_sc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8364 entries, 0 to 8363
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        8364 non-null   datetime64[ns]
 1   Documento    8364 non-null   int64
 2   Empresa      8364 non-null   object
 3   NCM4         8364 non-null   int64
 4   NCM6         8364 non-null   int64
 5   NCM8         8364 non-null   int64
 6   Posición     8364 non-null   int64
 7   Glosa        8364 non-null   object
 8   Detalle      8364 non-null   object
 9   Procedencia  8364 non-null   object
 10  Origen       8364 non-null   object
 11  FOB (USD)    8364 non-null   float64
 12  CIF (USD)    8364 non-null   float64
 13  Precio FOB   8364 non-null   float64
 14  Precio CIF   8364 non-null   float64
 15  Peso Neto    8364 non-null   float64
 16  Peso Bruto   8364 non-null   float64
 17  Vía          8364 non-null   object
 18  Proveedor    8227 non-null   object
 19  partida      8364 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(5), object(8)
memory usage: 1.3+ MB

In [16]:
df_sc['Fecha'] = pd.to_datetime(df_sc['Fecha'])

In [20]:
df_sc.groupby(['Posición'])['FOB (USD)'].sum()

Posición
25171000000    2.404220e+03
26070000000    4.562000e+03
27101213300    4.945462e+05
27101921000    3.734302e+07
27109900000    4.719900e+02
                   ...
96138000000    1.826000e+01
96200000300    2.050070e+03
96200000400    1.989910e+03
96200000900    3.567500e+02
98050000000    9.330000e+00
Name: FOB (USD), Length: 642, dtype: float64

In [21]:
df_sc.to_excel('San Cristobal.xlsx')